### ISSUE TITLE
Стили хранятся в массиве

### ISSUE THREAD

**Issue by cjbars** [7yon/Web-developing#6]
Не желательно хранить все подряд в массиве. Там должна остаться только логика, а все оформление должно переехать либо в css, ну или в css. Можно еще в css запихать. Но только не в свойство класса.

**Comment by 7yon** [comment]
fixed d23509558963cce8fd3cb6bc627915e14ee865c7

**Comment by cjbars** [comment]
неа не fixed
0 => array("href" =>"index.php", "img" => "./img/logo1.png", **"width" => 100, "height" => 60,**

**Comment by cjbars** [comment]
И вообще логотип это как бы другая сущность, оно к меню имеет весьма далекое отношение, просто рядом стоит, не находите?

**Comment by 7yon** [comment]
Не смогла придумать, как сделать это красиво :с 640945a239f17c7bb324c7ed8d08e3cb65798864

**Comment by cjbars** [comment]
Ну все правильно же сделали, стили в стили код в код
