### ISSUE TITLE
Ну и последняя зацепка

### ISSUE THREAD

**Issue by cjbars** [7yon/Web-developing#8]
Названия методов.
Смотрите, 
сможете по названию сказать что сделает метод Content::currentPage ?
а что делает метод Content::getMenu ?
по идее оба метода возвращают что-то рисуют, может их так и назвать renderЧтоТоТам?
Да и по задаче надо было возвращать сгенерированное содержимое, тоесть метод должен не просто нарисовать, а именно вернуть содержимое. 
Тогда можно будет это содержимое либо вывести, либо произвести над ним дополнительные действия.
И вот тогда методы уже должны будут называться getЧтоТоТам.

**Comment by 7yon** [comment]
теперь возвращают содержимое 640945a239f17c7bb324c7ed8d08e3cb65798864
