### ISSUE TITLE
Самая самая последняя правка

### ISSUE THREAD

**Issue by cjbars** [7yon/Web-developing#9]
Смотрите
`1 => array("href" => "index.php?page=1", "name" => "About", "style" => "bord", "id" => 1`
У вас единичка три раза используется в массиве, а если меню будет содержать 1000 пунктов?
Хотелось бы как то избавиться от избыточности в массиве, ведь сам ключ массива уже хранит достаточно инфармации

**Comment by 7yon** [comment]
640945a239f17c7bb324c7ed8d08e3cb65798864
